import { NextResponse } from 'next/server';
import { execSync, spawnSync } from 'child_process';
import { db } from '@/lib/server-deps';

export const dynamic = 'force-dynamic';

const REPO = 'tinyhumansai/openhuman';
const DISCORD_URL = 'https://discord.tinyhumans.ai/';

// Posts a friendly, personalized thank-you comment after a PR is merged.
// First-time contributors get a Discord invite; returning contributors get
// a thank-you only.
//
// The comment text is generated by `claude -p` so it can highlight
// something specific from the PR title/description. Everything is
// best-effort: if any step fails the merge has already happened, so we
// just report the error back without blocking.
export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id: idStr } = await params;
  const prId = parseInt(idStr, 10);

  try {
    // 1) Pull what we need about this PR + author.
    const view = JSON.parse(
      execSync(
        `gh pr view ${prId} --repo ${REPO} --json title,body,author,changedFiles,additions,deletions`,
        { encoding: 'utf-8', timeout: 15000, stdio: ['pipe', 'pipe', 'pipe'] },
      ),
    );
    const authorLogin: string = view.author?.login;
    const authorName: string | undefined = view.author?.name;
    if (!authorLogin) throw new Error('Could not determine PR author');

    // Skip team members entirely — welcome comments are for external
    // contributors. is_member is set by the github-sync worker from the
    // hardcoded ORG_MEMBERS list.
    const prRow = db.getPrById(prId);
    if (prRow?.is_member === 1) {
      return NextResponse.json({ posted: false, skipped: 'team_member', contributor: authorLogin });
    }

    // 2) First contribution check. After the merge this PR itself appears in
    // the merged list, so "first" = at most this PR (length <= 1).
    let isFirst = false;
    try {
      const prior = JSON.parse(
        execSync(
          `gh pr list --repo ${REPO} --author ${authorLogin} --state merged --json number --limit 5`,
          { encoding: 'utf-8', timeout: 15000, stdio: ['pipe', 'pipe', 'pipe'] },
        ),
      );
      isFirst = Array.isArray(prior) && prior.length <= 1;
    } catch {
      // If the lookup fails, default to NOT first (safer — no over-eager
      // Discord invite to a returning contributor).
      isFirst = false;
    }

    // 3) Craft the LLM prompt.
    const greeting = authorName && authorName !== authorLogin ? `${authorName} (@${authorLogin})` : `@${authorLogin}`;
    const description = (view.body || '').replace(/\r/g, '').slice(0, 400).trim();
    const stats = `+${view.additions}/-${view.deletions} across ${view.changedFiles} file${view.changedFiles === 1 ? '' : 's'}`;

    const prompt = [
      'Write a short, casual thank-you comment (2-3 sentences) to leave on a merged GitHub pull request.',
      '',
      `Contributor: ${greeting}`,
      `PR title: ${view.title}`,
      `Diff: ${stats}`,
      description ? `Description excerpt: ${description}` : '',
      isFirst
        ? `This is their FIRST merged PR to this repo. Invite them to our builder discord at ${DISCORD_URL} as exclusive access to a community of builders.`
        : 'They have contributed to this repo before. Thank them warmly but DO NOT mention discord or any invite.',
      '',
      'Style requirements:',
      '- ALL LOWERCASE. no capital letters anywhere, including names/handles.',
      '- casual, friendly tone, like talking to a teammate. a bit excited and hyped about the merge.',
      '- use 1 or 2 relevant emojis MAX across the whole comment. examples: 🙌 🚀 ✨ 💚 🎉 🔥.',
      '- NO em dashes (—) or en dashes (–). use commas, periods, or parens instead.',
      '- NO square brackets [] or angle brackets <> around step names, check names, or anything else. github tries to render those as markdown links / html and it looks broken. write step names as plain words, or wrap them in `backticks` if you want to set them apart.',
      '- address them by handle once.',
      '- call out one specific thing about this contribution (use the title or description).',
      '- no preamble like "here is the comment". no quotes around the output.',
      '- output only the comment body, ready to post verbatim.',
    ]
      .filter(Boolean)
      .join('\n');

    // 4) Run claude (non-interactive). spawnSync avoids shell-quoting the
    // multi-line prompt.
    const result = spawnSync('claude', ['-p', prompt], {
      encoding: 'utf-8',
      timeout: 90_000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    if (result.error) throw result.error;
    if (result.status !== 0) {
      throw new Error(`claude exited ${result.status}: ${(result.stderr || '').slice(0, 200)}`);
    }
    const comment = (result.stdout || '').trim();
    if (!comment) throw new Error('LLM returned empty response');

    // 5) Post the comment via gh. Use --body-file so multi-line content
    // round-trips without shell-quoting hell.
    const fs = await import('fs');
    const os = await import('os');
    const path = await import('path');
    const bodyFile = path.join(os.tmpdir(), `pr-${prId}-welcome-${Date.now()}.md`);
    fs.writeFileSync(bodyFile, comment + '\n');
    try {
      execSync(`gh pr comment ${prId} --repo ${REPO} --body-file ${bodyFile}`, {
        encoding: 'utf-8',
        timeout: 15000,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
    } finally {
      try { fs.unlinkSync(bodyFile); } catch {}
    }

    return NextResponse.json({ posted: true, comment, first_contribution: isFirst, contributor: authorLogin });
  } catch (err: any) {
    const msg = (err.stderr || err.message || '').toString();
    console.warn(`[welcome] PR #${prId}: ${msg}`);
    return NextResponse.json({ posted: false, error: msg }, { status: 500 });
  }
}
